# Common Application properties (az osszes konfiguracios lehetoseg)
# https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html
spring:
  application:
    name: actuatorproba

server:
  port: 9000
  error:
    path: /error2

management:
  security:
    enabled: false
  server:
    port: 9001
    address: 127.0.0.1
  endpoints:
    web:
      exposure:
        include: "*"     # E nelkul 90% nem muxik (the only two available by default are /health and /info.) !!!
      exclude: loggers # "Do NOT expose this one"

# https://www.baeldung.com/spring-boot-shutdown
endpoint:
  shutdown:
    enabled: true

endpoints:
  shutdown:
    enabled: true